# This prefix will appear when performing one of teams of a plugin #
CmdPrefix: "&8[&dxChat&8]"

# Messages List #
commands:
  RELOAD: "&dConfiguration files reloaded."
  MUTE: "&7You mute &d'<target>'"
  MUTE-ANNOUNCE: "&7Player &d'<target>' &7has muted by &d'<player>'"
  MUTE-DESC: "&7Error in command syntax, use &d/mute <playername>"
  UNMUTE: "&7You unmute &d'<target>'"
  UNMUTE-ANNOUNCE: "&7Player &d'<target>' &7has unmuted by &d'<player>'"
  FORMAT: "&dYou successful updated default chat formatting!"
  GROUP-FORMAT: "&7You set chat formatting for &d'<group>'"
chat:
  MUTED: "&cYou are muted by &d'%mutedBy%'"