###=_1######0000#.###########
#### LightEye™ #.#  sdir01 #
###99320##013###.###########

general:
  # Use debug mode, only for developers or server admins #
  debug-mode: false
  # Configuration version, don't touch this parameter #
  config-version: 1