# xChat developed by impact #
# This prefix will appear when performing one of teams of a plugin #
global:
  prefix: "&7[&bxChat&7]"

# Messages List #
messages:
  RELOAD: "&dConfiguration files reloaded."
  MUTE: "&7You mute &d'<target>'"
  MUTE-ANNOUNCE: "&7Player &d'<target>' &7has muted by &d'<player>'"
  MUTE-DESC: "&7Error in command syntax, use &d/mute <playername>"
  UNMUTE: "&7You unmute &d'<target>'"
  UNMUTE-ANNOUNCE: "&7Player &d'<target>' &7has unmuted by &d'<player>'"
  FORMAT: "&dYou successful updated default chat formatting!"
  GROUP-FORMAT: "&7You set chat formatting for &d'<group>'"
  CHAT-TARGET:
    MUTED: "&cYou are muted by &d'%mutedBy%'"