# This prefix will appear when performing one of teams of a plugin #
CmdPrefix: "&8[&dxChat&8]"

# Messages List #
commands:
  RELOAD: "&aConfiguration files reloaded."
  MUTE: "&7You mute &6'<target>'"
  MUTE-ANNOUNCE: "&7Player &c'<target>' &7has muted by &a'<player>'"
  ALREADY-MUTED: "&cYou already mute &6'<target>'"
  MUTE-DESC: "&aError in command syntax, use &e/mute <playername>"
  UNMUTE: "&7You unmute &6'<target>'"
  UNMUTE-ANNOUNCE: "&7Player &a'<target>' &7has unmuted by &a'<player>'"
  UNALREADY-MUTED: "&cPlayer &6'<target>' &cnot muted."
  UNMUTE-DESC: "&aError in command syntax, use &e/unmute <playername>"
chat:
  MUTED: "&cYou are muted by &e'%mutedBy%'"